name: Lint and Push to Dev-Pull

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # We will use our own SSH key for authentication
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff Linter
      run: ruff check --fix .
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Push changes to Dev-Pull
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_EMAIL: ${{ github.event.pusher.email || 'default-email@example.com' }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_EMAIL}"
        git add -A
        git commit -m "Apply automatic RUFF fixes"
        git push git@github.com:${{ github.repository }}.git Dev-Pull
