name: Lint and Push to Dev-Pull

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # We will use our own SSH key for authentication
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff Linter and save output
      id: ruff_lint
      run: |
        mkdir -p .github/workflows
        ruff check --fix . 2>&1 | tee .github/workflows/ruff_output.txt
    - name: Check for changes
      id: check_changes
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "All checks passed" >> .github/workflows/ruff_output.txt
          echo "no_changes=true" >> $GITHUB_ENV
        else
          git diff >> .github/workflows/ruff_output.txt
          echo "no_changes=false" >> $GITHUB_ENV
        fi
    - name: Print Ruff Linter Output
      run: cat .github/workflows/ruff_output.txt
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Push changes to Dev-Pull
      if: env.no_changes == 'false'
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_EMAIL: ${{ github.event.pusher.email || 'default-email@example.com' }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_EMAIL}"
        git add -A
        git commit -m "Apply automatic RUFF fixes"
        git push git@github.com:${{ github.repository }}.git Dev-Pull
