name: Lint and Commit

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff Linter
      run: ruff check --fix .
    - name: Commit changes
      if: github.ref == 'refs/heads/Dev-pull'
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_EMAIL: ${{ github.event.pusher.email }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_EMAIL}"
        git add -A
        git commit -m "Apply automatic RUFF fixes"
        git push
